"""init

Revision ID: 8f4a20f93aa0
Revises: 
Create Date: 2025-08-30 11:56:07.167011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4a20f93aa0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_levels_order', 'levels', ['order'], unique=False)
    op.create_table('players',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prizes',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_prizes',
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.Column('prize_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prize_id'], ['prizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'is_primary', name='uq_level_primary_once'),
    sa.UniqueConstraint('level_id', 'prize_id', name='uq_level_prize')
    )
    op.create_index(op.f('ix_level_prizes_level_id'), 'level_prizes', ['level_id'], unique=False)
    op.create_index(op.f('ix_level_prizes_prize_id'), 'level_prizes', ['prize_id'], unique=False)
    op.create_table('player_history',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.Column('prize_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prize_id'], ['prizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'level_id', name='uq_history_player_level')
    )
    op.create_index('ix_history_player_level', 'player_history', ['player_id', 'level_id'], unique=False)
    op.create_index(op.f('ix_player_history_level_id'), 'player_history', ['level_id'], unique=False)
    op.create_index(op.f('ix_player_history_player_id'), 'player_history', ['player_id'], unique=False)
    op.create_table('player_levels',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'level_id', name='uq_player_level')
    )
    op.create_index('ix_player_level', 'player_levels', ['player_id', 'level_id'], unique=False)
    op.create_index(op.f('ix_player_levels_level_id'), 'player_levels', ['level_id'], unique=False)
    op.create_index(op.f('ix_player_levels_player_id'), 'player_levels', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_levels_player_id'), table_name='player_levels')
    op.drop_index(op.f('ix_player_levels_level_id'), table_name='player_levels')
    op.drop_index('ix_player_level', table_name='player_levels')
    op.drop_table('player_levels')
    op.drop_index(op.f('ix_player_history_player_id'), table_name='player_history')
    op.drop_index(op.f('ix_player_history_level_id'), table_name='player_history')
    op.drop_index('ix_history_player_level', table_name='player_history')
    op.drop_table('player_history')
    op.drop_index(op.f('ix_level_prizes_prize_id'), table_name='level_prizes')
    op.drop_index(op.f('ix_level_prizes_level_id'), table_name='level_prizes')
    op.drop_table('level_prizes')
    op.drop_table('prizes')
    op.drop_table('players')
    op.drop_index('ix_levels_order', table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
